### ISSUE TITLE
Ska courtage för försäljning inkluderas i omkostnadsbeloppet?

### ISSUE THREAD

**Issue by JohanLarsson** [JohanLarsson/IbkrToSru#1]

**Comment by fmeta** [comment]
Ja courtage för både inköp och försäljning räknas med i omkostnadsbeloppet. Se skatteverkets räkneexempel:
https://skatteverket.se/privat/skatter/vardepapper/deklareraaktierochovrigavardepapper/deklareravardepapperexempel.4.7afdf8a313d3421e9a9519.html

**Comment by JohanLarsson** [comment]
I exemplet subtraheras courtage från försäljningspriset.
Jag mailade skatteverket och frågade.
Har uppdaterat koden men glömde att stänga den här tråden, stänger den nu.
